### ISSUE TITLE
Project structure and scaffolding

### ISSUE THREAD

**Issue by karimamer** [arrdem/reidis#1]
We need to come up with Project structure

**Comment by arrdem** [comment]
first we need a build tool that doesn't suck @stdlib

**Comment by thoughtpolice** [comment]
use [shake](http://shakebuild.com) to write build rules and [nix](http://nixos.org/nix) to provision your environment. BOOM.

the bad news is this: it's _actually_ possible your build system will still suck. good news: if it does, it will be your fault, and it will always suck in a perfectly reproducible way, at the very least.

(in all seriousness this is the combo we use at $WORK and it works pretty fantastically for the most part. one of these days I'll combine the two somehow into the ultimate purely functional build system...)
